@startuml CustomerUC
left to right direction

'Actor
:Customer: as customer
:Employee: as employee

'Use cases
(Book a room) as UC1
(View a booked room) as UC2
(Request amenities) as UC3
(Cancel a room) as UC4

'Associations
customer --> UC1
customer --> UC2
customer --> UC3
customer --> UC4
UC3 --> employee
UC4 --> employee



@enduml