@startuml MHS
title Marwaan's Hotel System
top to bottom direction
skinparam linetype ortho

package MHS <<Rectangle>> {
    together {

        abstract Class Account <<abstract>>{
            firstName
            lastName
            email
            password
            phoneNumber
        }

        Class StaffAccount {
            void editBooking()
        }

        Account <|-down- StaffAccount
        Account <|-down- Customer

        Class Manager {
            void setOpeningHour()
            void setClosingHour()
            void createRoom()
            void changeRoom()
            void createShift()
            void modifyShift()
            void hireEmployee()
            void fireEmployee()
        }

        Class Employee {
            type : EmployeeType
        }

        StaffAccount <|-down- Manager
        StaffAccount <|-down- Employee


        Class Customer {
        }
    }
    Class Guest

    together {

        Class Room {
            type : RoomType
            bed : BedType
            pricePerNight
        }

        Class Booking {
            numberOfGuest
            checkinDate
            checkoutDate
        }

        Class Request {
            customerName
            room : Room
            description
        }
    }


    Class Hotel {
        openingHour
        closingHour
    }

    Class Payment {
        amount
        id
    }

    Class Shift {
        date
        startTime
        endTime
    }

    Class Schedule


    Manager --> Room
    Manager --> Hotel

    Manager -left-> Employee
    StaffAccount --> Request

    Employee --> Shift

    Manager --> Shift

    Booking -- Payment
    Booking --> Request

    Room -up- Customer
    (Customer, Room) .right. Booking

    Guest -down- Room
    (Guest, Room) ... Booking
    Shift -right-* Schedule

    enum RoomType {
        Suite
        Deluxe
        Luxury
        Regular
    }

    enum BedType {
        King
        Queen
        Doubles
    }

    enum EmployeeType {
        KitchenStaff
        CleaningStaff
        Reception
    }
    note left of BedType::Doubles
    2 double-sized beds
    end note
}
@enduml