@startuml MHS
title Marwaan's Hotel System
skinparam linetype ortho
top to bottom direction

package MHS <<Rectangle>> {
    Class User {
        firstName
        lastName
        email
        phone : int
    }

    Class Account {
        password
    }

    Class Employee {
        hoursWorked : int
    }

    Class Manager {
    }

    Class Customer {
    }

    ' Associations of users
    User    <|-- Account
    Account <|-- Employee
    Account <|-- Customer
    Account <|-- Manager

    ' Employees and their shifts/schedule
    Class Shift {
        date : date
        startTime : int
        endTime : int
    }

    Shift "*" -left-> "1" Employee

    Class Schedule

    Shift "1" -down-* "1..*" Schedule

    ' Room, Booking, Request, Payment 
    Class Room {
        type : RoomType
        bed : BedType
        isAvailable : boolean
        pricePerNight : int
        maxCapacity : int
    }

    Room "70" -left-* "1" Hotel

    Class Booking {
        # bookingId
    }

    Booking "1" -left-> "1" Room
    Booking "1" -right-> "1" User

    Class Request {
        description : string
    }

    Request "1" -down-> "1" Employee
    Request "1" -up-> "1" Booking

    Class Payment {
        amount : int
        # paymentId 
    }

    Booking "1" -up-> "1" Payment

    ' Hotel, Hotel Hours of Operations

    Class Hotel {
    }

    Hotel "1" -left-> "1" HotelSchedule

    Class HotelSchedule {
        year : int
    }

    Class OperatingHours {
        day : DayOfWeek
        openingHour : int
        closingHour : int
    }

    Class CustomHours {
        date : date
        openingHour : int
        closingHour : int
    }

    HotelSchedule "1" -down-> "365" CustomHours
    HotelSchedule "1" -up-> "7" OperatingHours

    
    together {
        top to bottom direction
        enum RoomType <<enum>> {
            Suite
            Deluxe
            Luxury
            Regular
        }

        enum BedType <<enum>> {
            King
            Queen
            Doubles
        }

        enum DayOfWeek <<enum>> {
            Monday
            Tuesday
            Wednesday
            Thursday
            Friday
            Saturday
            Sunday
        }
    }
}
@enduml