@startuml CustomerUC
title
FR2 - The MHS system shall allow a customer with or without an account
to book a specific room type and pay for their room booking
end title

left to right direction

'Actor
:Customer: as customer
:Guest: as guest

'Use cases
node MHS {
    (Book room) as UC1
    (Select room) as UC2
    (Pay for room) as UC3
    (Enter personal information) as UC4
    (Log in) as UC5
    (Enter credentials) as UC6
    (Enter room criteria) as UC7
}

'Associations
customer --> UC1
UC2 -right.> UC1: <<includes>>
UC3 -up.> UC1: <<includes>>
guest --> UC1
UC4 -up.> UC1: <<includes>>
UC5 -left.> UC1: <<extends>>
UC6 -up.> UC5: <<includes>>
UC7 -up.> UC2: <<includes>>

@enduml