@startuml CustomerUC
'FR4 - The MHS shall allow a customer with an account to make specific requests regarding their room

title FR4 - The MHS shall allow customers with an account to make requests regarding their room.
'Use cases

node MHS {
(Add request to booking) as UC0
(Book room) as UC1
(Select room) as UC2
(Login) as UC5
(Pay) as UC11
(Write special request) as UC17

left to right direction

'Associations
UC0 <-.- UC1  : includes
UC1 <-.- UC2 : includes
UC1 <-.- UC17 : extends
UC1 <-.- UC5 : includes
UC1 <-.- UC11 : includes
}
Customer --> UC0
paymentAuthenticator --> UC11 : includes
LoginAuthenticator --> UC5 : includes






@enduml