@startuml CustomerUC
'FR4 - The MHS shall allow a customer with an account to make specific requests regarding their room
title FR4 - The MHS shall allow customers with an account to make requests regarding their room at any time before the end of their stay, \n and customers without an account to make requests at the time of booking.
'Use cases
node MHS {
(Add request while booking) as UC0_0
(Book room) as UC0_1
(Write special request) as UC0_2
(Add request after booking) as UC1_0
(Log in to account) as UC1_1
(Write special request) as UC1_2
(Navigate to booking) as UC1_3
(Request an additional service) as UC1_4
(Confirm addition of request) as UC1_5

left to right direction
'Associations
UC0_0 <-.- UC0_1 : extends
UC0_0 <-.- UC0_2 : includes
UC1_3 <-.- UC1_1 : includes
UC1_0 <-.- UC1_3: includes
UC1_3 <-.- UC1_4: extends
UC1_4 <-.- UC1_2 : includes
UC1_4 <-.- UC1_5 : extends



}
Guest --> UC0_0
Customer --> UC0_0
Customer --> UC1_0
