@startuml ShiftManagementUC
title FR8: The manager shall be able to set and modify shifts for the employees.

' Actor
:Manager: as manager

node MHS {
    ' Use cases
    (Set employee shifts) as UC1
    (Modify existing shifts) as UC2
    (Enter shift date) as UC3
    (Enter start and end times) as UC4
    (Assign employee) as UC5
    (Press 'Add Shift') as UC6
    (Press 'Modify Shift') as UC7

    ' Associations
    left to right direction
    UC3 .up.> UC1 : includes
    UC4 .up.> UC1 : includes
    UC5 .up.> UC1 : includes
    UC6 .left.> UC1 : includes
    UC3 ..> UC2 : excludes
    UC4 ..> UC2 : excludes
    UC5 ..> UC2 : excludes
    UC7 .left.> UC2 : includes
}


manager -left-> UC1
manager --> UC2


@enduml
