name: Backend Build without Test

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "backend/**"

permissions:
  contents: read

jobs:
  compile:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Install Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.2.1
    - name: Compile with Gradle
      run: |
        gradle build -xtest
      working-directory: ${{ env.working-directory }}
